# goal definition
geometry_msgs/PoseStamped goal
bool force
---
# result definition
uint8 SUCCESS = 1
uint8 FAILED = 2
uint8 TIMEOUT = 3
uint8 NO_PATH = 4
uint8 CANCELLED = 5
uint8 status
---
# feedback
# no feedback
